import fs from "fs";
import path from "path";

// Build-time data for the field. Everything printed on the page is
// real — git metadata and pre-baked portrait states are generated by
// scripts/build-meta.mjs, scripts/prepare-portrait.mjs and
// scripts/prepare-art.mjs before the build; when a file is missing we
// degrade honestly, never invent.

export interface BuildLogEntry {
  date: string;
  dow: string;
  subject: string;
}

export interface ActivityMonth {
  month: string;
  count: number;
}

export interface BuildMeta {
  shortHash: string;
  buildDate: string;
  buildYear: number;
  commitCount: number;
  lastUpdatedDays: number | null;
  log: BuildLogEntry[];
  activity: ActivityMonth[];
}

const FALLBACK_META: BuildMeta = {
  shortHash: "0000000",
  buildDate: "unknown",
  buildYear: new Date().getFullYear(),
  commitCount: 0,
  lastUpdatedDays: null,
  log: [],
  activity: [],
};

function readText(rel: string): string | null {
  try {
    return fs.readFileSync(path.join(process.cwd(), rel), "utf8");
  } catch {
    return null;
  }
}

export function getBuildMeta(): BuildMeta {
  const raw = readText("lib/generated/build-meta.json");
  if (!raw) return FALLBACK_META;
  try {
    return { ...FALLBACK_META, ...JSON.parse(raw) };
  } catch {
    return FALLBACK_META;
  }
}

function readAsciiJson(rel: string): string[] | null {
  const raw = readText(rel);
  if (!raw) return null;
  try {
    const data = JSON.parse(raw) as { lines: string[] };
    return Array.isArray(data.lines) && data.lines.length ? data.lines : null;
  } catch {
    return null;
  }
}

export function getAsciiPortrait(): string[] {
  return readAsciiJson("lib/generated/avatar-ascii.json") ?? ["  (portrait not recovered)  "];
}

export function getAsciiPortraitLarge(): string[] | null {
  return readAsciiJson("lib/generated/avatar-ascii-large.json");
}

export function hasPublicFile(rel: string): boolean {
  try {
    return fs.existsSync(path.join(process.cwd(), "public", rel));
  } catch {
    return false;
  }
}

export function hasPortraitImages(): boolean {
  return hasPublicFile("generated/avatar-atkinson.png");
}

// inline SVG markup of the contour map, or null when not generated
export function getContourSvg(): string | null {
  const raw = readText("public/generated/contour.svg");
  if (!raw || !raw.includes("<svg")) return null;
  return raw;
}
