import fs from "fs";
import path from "path";

// Build-time data for the field. Everything printed on the page is
// real — git metadata and pre-baked portrait states are generated by
// scripts/build-meta.mjs and scripts/prepare-portrait.mjs before the
// build; when a file is missing we degrade honestly, never invent.

export interface BuildLogEntry {
  date: string;
  dow: string;
  subject: string;
}

export interface BuildMeta {
  shortHash: string;
  buildDate: string;
  buildYear: number;
  commitCount: number;
  lastUpdatedDays: number | null;
  log: BuildLogEntry[];
}

const FALLBACK_META: BuildMeta = {
  shortHash: "0000000",
  buildDate: "unknown",
  buildYear: new Date().getFullYear(),
  commitCount: 0,
  lastUpdatedDays: null,
  log: [],
};

export function getBuildMeta(): BuildMeta {
  try {
    const raw = fs.readFileSync(
      path.join(process.cwd(), "lib/generated/build-meta.json"),
      "utf8"
    );
    return { ...FALLBACK_META, ...JSON.parse(raw) };
  } catch {
    return FALLBACK_META;
  }
}

export function getAsciiPortrait(): string[] {
  try {
    const raw = fs.readFileSync(
      path.join(process.cwd(), "lib/generated/avatar-ascii.json"),
      "utf8"
    );
    const data = JSON.parse(raw) as { lines: string[] };
    if (Array.isArray(data.lines) && data.lines.length) return data.lines;
  } catch {}
  return ["  (portrait not recovered)  "];
}

export function hasPortraitImages(): boolean {
  try {
    return fs.existsSync(
      path.join(process.cwd(), "public/generated/avatar-atkinson.png")
    );
  } catch {
    return false;
  }
}
