import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const ROOT = process.cwd();
const POSTS_DIR = path.join(ROOT, "content", "posts");
const OUT_FILE = path.join(ROOT, "lib", "posts.generated.ts");
const SLUG_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

interface RawPost {
  slug: string;
  frontmatter: Record<string, unknown>;
  content: string;
}

function collect(): RawPost[] {
  if (!fs.existsSync(POSTS_DIR)) return [];

  const entries = fs.readdirSync(POSTS_DIR).filter((f) => f.endsWith(".md"));
  const posts: RawPost[] = [];

  for (const file of entries) {
    const slug = file.replace(/\.md$/, "");
    if (!SLUG_PATTERN.test(slug)) {
      console.warn(`[build-posts] skipping invalid slug: ${file}`);
      continue;
    }
    const source = fs.readFileSync(path.join(POSTS_DIR, file), "utf8");
    const { data, content } = matter(source);
    posts.push({ slug, frontmatter: data, content });
  }

  return posts;
}

function emit(posts: RawPost[]): string {
  const banner =
    "// AUTO-GENERATED by scripts/build-posts.ts — do not edit by hand.\n" +
    "// Run `bun run build:posts` to regenerate.\n\n";

  const body =
    "import type { Post } from \"./blog-types\";\n\n" +
    `export const posts: Post[] = ${JSON.stringify(posts, null, 2)};\n`;

  return banner + body;
}

const posts = collect();
fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, emit(posts), "utf8");
console.log(`[build-posts] wrote ${posts.length} post(s) → ${path.relative(ROOT, OUT_FILE)}`);
