name: CI for dev branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Set up Node.js (for linting)
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Lint Code
        run: npx next lint --fix

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Docker image
        run: |
          docker build -t nsvk13-website:${{ github.sha }} .

      - name: Save Docker image as tar
        run: |
          docker save nsvk13-website:${{ github.sha }} -o nsvk13-website-${{ github.sha }}.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: nsvk13-website-${{ github.sha }}.tar
