name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            - name: Lint check
              run: bun run lint