name: CI for dev branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint Code
        run: bun lint

  test:
      runs-on: ubuntu-latest
      needs: lint

      steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Bun
            uses: oven-sh/setup-bun@v1

          - name: Install dependencies
            run: bun install

          - name: Run tests
            run: bun test
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Docker image
        run: |
          docker build -t nsvk13-website:${{ github.sha }} .

      - name: Upload Docker iamge as artifact
        uses: actions/upload-artifact@v2
        with:
            name: docker-image
            path: ./nsvk13-website:${{ github.sha }}.tar