name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                docker build -t nsvk13-webiste:${{ github.sha }} .

            - name: Push Docker image
              run: |
                dokcer push nsvk13-website:${{ github.sha }}

            # - name: Deploy application (need server lul)
            #  run: |
              # ssh user@hostname "docker pull nsvk13-website:${{ github.sha }} && docker run -d nsvk13-website:${{ github.sha }}"
              # echo "Deploying Docker container.."